apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bgottfried91/Gloo-Edge-Gitops.git'
    path: helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: httpbin-helm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

