apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bgottfried91/Gloo-Edge-Gitops.git'
    path: httpbin-manifests
    targetRevision: HEAD
    directory:
      jsonnet:
        tlas:
          - name: ''
            value: ''
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: httpbin
